name: compile and run test programs
on:
  push:
    paths:
      - unix-creds/xuid.c
  workflow_dispatch:
jobs:
  compile-and-run:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-26, macos-latest, macos-14]
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: ${{matrix.os}}
        run: |
          cd unix-creds
          make xuid
          sudo ./xuid
