name: compile and run test programs
on:
  push:
    paths:
      - unix-creds/xuid.c
jobs:
  compile-and-run:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, macos-26, macos-latest, macos-14]
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: ${{matrix.os}}
        run: |
          cc -Wall unix-creds/xuid.c -o xuid
          sudo ./xuid
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: vmactions/solaris-vm@v1
        with:
          run: |
            sudo pkg install developer/gcc
            cc unix-creds/xuid.c -o xuid
            sudo ./xuid
        uses: vmactions/netbsd-vm@v1
        with:
          run: |
            cc unix-creds/xuid.c -o xuid
            sudo ./xuid
